### ISSUE TITLE
Game crashing on 20w05b

### ISSUE THREAD

**Issue by DiamondMon** [Queerbric/Inspecio#3]
Basically, whenever I try to join a server on Minecraft version 20w05b, the game crashes

Idk if this is required but here is the crash report:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 14/02/21 15:25
Description: Unexpected error

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_634.method_11120(class_634.java:351)
	at net.minecraft.class_2678.method_11567(class_2678.java:112)
	at net.minecraft.class_2678.method_11054(class_2678.java:19)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_2600$$Lambda$4178/218626666.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.class_310.method_1523(class_310.java:1020)
	at net.minecraft.class_310.method_1514(class_310.java:688)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [fabric-lifecycle-events-v1.mixins.json:client.ClientChunkManagerMixin] from phase [DEFAULT] in config [fabric-lifecycle-events-v1.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 25 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on onChunkLoad could not find any targets matching 'Lnet/minecraft/class_631;method_16020(IILnet/minecraft/class_4548;Lnet/minecraft/class_2540;Lnet/minecraft/class_2487;I)Lnet/minecraft/class_2818;' in net.minecraft.class_631. Using refmap fabric-lifecycle-events-v1-refmap.json [PREINJECT Applicator Phase -> fabric-lifecycle-events-v1.mixins.json:client.ClientChunkManagerMixin -> Prepare Injections ->  -> handler$zzo000$onChunkLoad(IILnet/minecraft/class_4548;Lnet/minecraft/class_2540;Lnet/minecraft/class_2487;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 21w05b
	Minecraft Version ID: 21w05b
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 953264488 bytes (909 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.28.3+1.17
		fabric-api-base: Fabric API Base 0.2.0+eaafab808e
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+836e66a38e
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+9f7a74238e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+9f7a74238e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+9f7a74238e
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+bee3a8868e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+880269e68e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d8e
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+e1f1abb18e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+9f7a74238e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+9f7a74238e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.4+3e817a628e
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+9f7a74238e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+9f7a74238e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c68e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+9f7a74238e
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.0+8f5b7a468e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+0c3d83a58e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+9f7a74238e
		fabric-models-v0: Fabric Models (v0) 0.1.1+9f7a74238e
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+fd1187378e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+bee3a8868e
		fabric-networking-v0: Fabric Networking (v0) 0.3.1+96f0bfaa8e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.2+9f7a74238e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+9f7a74238e
		fabric-particles-v1: fabric-particles-v1 0.2.2+9f7a74238e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+836e66a38e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.4+e1f1abb18e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+e1f1abb18e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.0.3+0c3d83a58e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+9f7a74238e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+9f7a74238e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+9f7a74238e
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+9f7a74238e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.0+27f445e78e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.3+9f7a74238e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.2+cc3cc6c68e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+e1f1abb18e
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+9f7a74238e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+9f7a74238e
		fabricloader: Fabric Loader 0.11.1
		inspecio: Inspecio 1.0.1+20w51a
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.17-alpha.21.5.b
	Launched Version: fabric-loader-0.11.1-21w05b
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 630 GL version 4.6.0 - Build 26.20.100.7925, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/netherite-plated-diamond-v3 (1).zip (incompatible), file/Shield+Corrections+[Colored].zip (incompatible), file/VanillaTweaks_r376495.zip (incompatible), file/Blue_Ancient_Debris.zip (incompatible)
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**Comment by LambdAurora** [comment]
Your Fabric API is outdated, you need Fabric API 0.30.2+1.17.
