### ISSUE TITLE
Crash on Init with Beacon Overhaul

### ISSUE THREAD

**Issue by Estrelaura** [Queerbric/Inspecio#32]
Same method as the last report causing the crash. Such a crashy boi. The weird/tricky part on this one is that Beacon Overhaul is nowhere to be found on the stacktrace.

> ---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

>Time: 8/31/21, 7:47 AM
Description: Initializing game

>java.lang.NullPointerException: Cannot invoke "io.github.queerbric.inspecio.Inspecio.getConfig()" because the return value of "io.github.queerbric.inspecio.Inspecio.get()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.9)
	at io.github.queerbric.inspecio.Inspecio.appendBlockItemTooltip(Inspecio.java:140)
	at net.minecraft.item.BlockItem.handler$can000$onAppendTooltipEnd(BlockItem:94)
	at net.minecraft.item.BlockItem.appendTooltip(BlockItem:210)
	at net.minecraft.item.ItemStack.getTooltip(ItemStack:677)
	at net.minecraft.client.MinecraftClient.method_1485(MinecraftClient:765)
	at net.minecraft.client.search.TextSearchableContainer.index(TextSearchableContainer:36)
	at net.minecraft.client.search.IdentifierSearchableContainer.add(IdentifierSearchableContainer:48)
	at net.minecraft.client.MinecraftClient.method_1535(MinecraftClient:778)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.MinecraftClient.initializeSearchableContainers(MinecraftClient:777)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:576)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

>-- Head --
Thread: Render thread
Stacktrace:
	at io.github.queerbric.inspecio.Inspecio.appendBlockItemTooltip(Inspecio.java:140)
	at net.minecraft.class_1747.handler$can000$onAppendTooltipEnd(io/github/queerbric/inspecio/mixin/BlockItemMixin.java [inspecio.mixins.json]:94)
	at net.minecraft.class_1747.method_7851(class_1747.java:210)
	at net.minecraft.class_1799.method_7950(class_1799.java:677)
	at net.minecraft.class_310.method_1485(class_310.java:765)
	at net.minecraft.class_1126.method_4795(class_1126.java:36)
	at net.minecraft.class_1121.method_4798(class_1121.java:48)
	at net.minecraft.class_310.method_1535(class_310.java:778)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_310.method_1546(class_310.java:777)
	at net.minecraft.class_310.<init>(class_310.java:576)
Mixins in Stacktrace:
	net.minecraft.class_1747:
		carpet.mixins.BlockItem_creativeNoClipMixin (carpet.mixins.json)
		dev.stashy.extrasounds.mixin.inventory.item.BlockItemSound (extrasounds.mixins.json)
		carpet.mixins.BlockItem_scarpetEventMixin (carpet.mixins.json)
		carpettisaddition.mixins.rule.blockPlacementIgnoreEntity.BlockItemMixin (carpet-tis-addition.mixins.json)
		io.github.queerbric.inspecio.mixin.BlockItemMixin (inspecio.mixins.json)
		carpetextra.mixins.BlockItemMixin_accurateBlockPlacement (carpet-extra.mixins.json)
		dev.architectury.mixin.fabric.MixinBlockItem (architectury.mixins.json)
		me.shedaniel.cloth.mixin.common.events.MixinBlockItem (cloth-common-events-v1.mixins.json)
	net.minecraft.class_1799:
		me.jellysquid.mods.lithium.mixin.item.ItemStackMixin (lithium.mixins.json)
		carpetextra.mixins.ItemStackMixin (carpet-extra.mixins.json)
		io.github.queerbric.inspecio.mixin.ItemStackMixin (inspecio.mixins.json)
		minitweaks.mixins.ItemStack_RepairCostMixin (minitweaks.mixins.json)
		me.jellysquid.mods.lithium.mixin.block.hopper.ItemStackMixin (lithium.mixins.json)
		net.fabricmc.fabric.mixin.item.client.ItemStackMixin (fabric-item-api-v1.mixins.json)
		squeek.appleskin.mixin.ItemStackMixin (appleskin.mixins.json)
		net.fabricmc.fabric.mixin.tool.attribute.MixinItemStack (fabric-tool-attribute-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.item.ItemStackMixin (fabric-item-api-v1.mixins.json)
		me.juancarloscp52.bedrockify.mixin.common.features.useAnimations.ItemStackMixin (bedrockify.mixins.json)
		net.flytre.stat_check.mixin.ItemStackMixin (stat_check.mixins.json)
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.command.client.MinecraftClientMixin (fabric-command-api-v1.mixins.json)
		xyz.starmun.justenoughkeys.mixin.MinecraftMixin (justenoughkeys.mixins.json)
		de.siphalor.mousewheelie.client.mixin.MixinMinecraftClient (mousewheelie.mixins.json)
		io.github.blobanium.lt.mixin.MinecraftClientMixin (loading-timer.mixins.json)
		com.minenash.pickblockstate.mixin.MinecraftClientMixin (pickblockstate.mixins.json)
		carpet.mixins.MinecraftClientMixin (carpet.mixins.json)
		dev.stashy.extrasounds.mixin.HotbarSlotSound (extrasounds.mixins.json)
		net.fabricmc.fabric.mixin.networking.accessor.MinecraftClientAccessor (fabric-networking-api-v1.mixins.json)
		me.shedaniel.advancementsenlarger.mixin.MixinMinecraftClient (advancements-enlarger.mixins.json)
		moe.caa.fabric.quitconfirm.client.mixin.MixinMinecraftClient (quitconfirm.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.mixins.json)
		io.socol.betterthirdperson.mixin.MinecraftClientMixin (betterthirdperson.mixins.json)
		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
		me.juancarloscp52.bedrockify.mixin.client.features.reacharoundPlacement.MinecraftClientMixin (bedrockify.mixins.json)
		carpet.mixins.MinecraftClient_pausedShakeMixin (carpet.mixins.json)
		me.shedaniel.slightguimodifications.mixin.MixinMinecraft (slight-gui-modifications.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MixinMinecraftClient (fabric-registry-sync-v0.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.MixinMinecraftClient (fabric-events-interaction-v0.mixins.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
		fudge.notenoughcrashes.mixins.client.CatchInitMInecraftClientMixin (notenoughcrashes.fabric.mixins.json)
		net.ludocrypt.dynmus.mixin.MinecraftClientMixin (dynmus.mixins.json)
		fudge.notenoughcrashes.mixins.client.MixinMinecraftClient (notenoughcrashes.mixins.json)
		com.github.lotqwerty.lottweaks.fabric.mixin.VanillaPickInvoker (lottweaks.mixins.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		me.juancarloscp52.bedrockify.mixin.client.core.clientRenderTimer.MinecraftClientMixin (bedrockify.mixins.json)
		me.shedaniel.cloth.mixin.client.events.MixinMinecraftClient (cloth-client-events-v0.mixins.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		net.clayborn.accurateblockplacement.mixin.MinecraftClientMixin (accurateblockplacement.mixins.json)
		dynamicfps.mixin.MinecraftClientMixin (dynamicfps.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		agency.highlysuspect.autothirdperson.mixin.MinecraftClientMixin (auto_third_person.mixins.json)
		adudecalledleo.dontdropit.mixin.MinecraftClientMixin (dontdropit.mixins.json)

>-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		fudge.notenoughcrashes.mixins.client.MixinMain (notenoughcrashes.fabric.mixins.json)

>-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 994390528 bytes (948 MiB) / 2099249152 bytes (2002 MiB) up to 2099249152 bytes (2002 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 750 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1380
	Graphics card #0 versionInfo: DriverVersion=27.21.14.5671
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 13729.49
	Virtual memory used (MB): 8095.39
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 2370.25
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2001m -Xmx2001m
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.10
		adaptivebrightness: Adaptive Brightness 1.0.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		advancementplaques: Advancement Plaques 1.4.0
		advancements-enlarger: Advancements Enlarger 0.2.4
		amecsapi: Amecs API 1.1.5+mc21w16a
		antighost: AntiGhost 1.17.1-fabric0.36.1-1.1.4
		appleskin: AppleSkin mc1.17-2.1.3
		architectury: Architectury 2.5.27
		augmentedautojump: Augmented Autojump 1.1.0
		auto_third_person: Auto Third Person 1.1.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axesareweapons: Axes Are Weapons 1.3-1.17
		axolotlitemfix: Axolotl Item Fix 1.1.2
		beaconoverhaul: Beacon Overhaul 1.4.1+1.17
		bedrockify: BedrockIfy 1.1.2+mc1.17.1
		betterf3: BetterF3 1.1.5
		bettermounthud: Better Mount HUD 1.1.2
		betterthirdperson: Better Third Person 1.5.0
		big_items_duh: Big items, duh! 1.0.2+mc1.17-rc2
		blur: Blur (Fabric) 2.1.0
		cakechomps: Cake Chomps 1.4.0-1.17
		camp_fires_cook_mobs: Camp Fires Cook Mobs 1.2.1+MC1.17-1.17.1
		carpet: Carpet Mod 1.4.45
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.21.2+build.655
		cauldronconcrete: Cauldron Concrete 1.0.0+21w16a-fabric
		cauldronriptide: Cauldron Riptide 1.1-mc1.17-fabric
		centeredinventory: Centered inventory 1.0.0
		chainsuspension: Chain Suspension 1.0.0
		clear-skies: Clear Skies 1.5.70
		clientsidenoteblocks: ClientSideNoteblocks 2.0
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		colorfulsubtitles: Colorful Subtitles 1.0.0
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.5.0+1.17
		creativeonepunch: Creative One-Punch 1.2
		creeperaiupdated: Creeper AI Updated 1.4.0
		crosshairmod: Crosshair Mod 0.3.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customstars: Custom Stars 0.5
		datareload: Data Reload 1.1
		detailab: Detail Armor Bar 2.4.1+1.17.1-fabric
		dontdropit: Don't Drop It! 2.3.1+1.17
		dynamicfps: Dynamic FPS 2.0.5
		dynmus: Dynamic Music 1.3.0
		enchantment_lore: EnchantmentLore 1.2.1+MC1.17.1
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.2+1.17
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		extrasounds: Extra Sounds 1.4.1
		fabric: Fabric API 0.39.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+2f75c6ce18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+b06cb95b18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+211ddf9518
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.2+62e33f4118
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.1+b06cb95b18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.0+b06cb95b18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+e72a3bf490
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.1.2+96bf6a7e18
		fabricloader: Fabric Loader 0.11.6
		fabulousclouds: Fabulous Clouds 0.2.3
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		ferritecore: FerriteCore 3.0.3
		flytre_lib: FlytreLib 0.2.21
		fuelinfo: FuelInfo 1.0
		hatlist: Hat List 1.2
		headsdowndisplay: Heads down display 0.0.0
		hydrogen: Hydrogen 0.3
		illuminations: Illuminations 1.7
		indium: Indium 1.0.0+mc1.17.1
		inspecio: Inspecio 1.1.0+1.17
		itemmodelfix: Item Model Fix 1.0.2+1.17
		java: OpenJDK 64-Bit Server VM 16
		justenoughkeys: Just Enough Keys 0.2.2
		kirin: Kirin UI 1.9.1
		krypton: Krypton 0.1.4
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		light-fix: light-fix 1.0.0
		lithium: Lithium 0.7.4
		loading-timer: Loading Timer 1.5.0-Beta1
		lottweaks: LotTweaks 2.0.4beta01
		mcwifipnp: Minecraft WLAN Plug-n-Play 1.4.7
		minecraft: Minecraft 1.17.1
		minitweaks: MiniTweaks 1.1.2
		mixintrace: MixinTrace 1.1.0+1.17
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 2.0.7
		mojangster: Mojangster 1.17-1.3.0
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17.1-pre1
		musicdr: Music Duration Reducer 1.2.1
		namepain: Name Pain 1.4.0
		nethermap: Better Nether Map 1.4.0-1.17.1
		not-that-cc: Crafty Crashes 1.0
		notenoughanimations: NotEnoughAnimations 1.3.0
		notenoughcrashes: Not Enough Crashes 3.4.4+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		particlerain: Particle Rain 1.4.1
		pickblockstate: Pick-BlockState 1.0.0+1.17
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		prettycapes: PrettyCapes 1.2-Fabric1.17
		quickspyglasser: Quick Spyglasser 0.3.0
		quitconfirm: QuitConfirm 1.3
		rad: Reload Audio Driver 1.0.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		recipecache: recipecache 0.2.0-1.17.1
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		satin: Satin 1.6.0-nightly.1.17-pre3
		searchablecontainers: Searchable Containers 1.3
		skinlayers: 3d Skin Layers 1.0.1
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.1
		smoothswapping: Smooth Swapping 0.4.2
		sodium: Sodium 0.3.2+build.7
		soundphysics: Sound Physics 2.0.0
		spruceui: SpruceUI 3.3.0+1.17
		spyzoom: Spyglass Zoom 1.0.1
		starlight: Starlight 1.0.0+fabric.73f6d37
		stat_check: Stat Check 1.1.0
		telepistons: Telepistons 1.0.2
		tooltipfix: ToolTip Fix 1.0.3-1.16
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		transliterationlib: TRansliterationLib 1.1.0
		tweed: Tweed 3.0.0-beta.26
		undergroundambientlighting: Underground Ambient Lighting 2.0.0
		vectorientation: Vectorientation 1.0.1a
		visuality: Visuality 0.1.0
		waig: Where Am I Going 1.0.0
		waterdripsound: Drip Sounds 1.17-0.2.2
		waveycapes: WaveyCapes 1.0.1
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 750 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 456.71, NVIDIA Corporation
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
	Suspected Mods: Inspecio (inspecio), Fabric Loader (fabricloader)

**Comment by Estrelaura** [comment]
Not a problem with the mod, see #31
