### ISSUE TITLE
REI async search can cause crash

### ISSUE THREAD

**Issue by Fourmisain** [Queerbric/Inspecio#39]
I was searching for potions in REI after just having booted the game when this happened:
<details>
<summary>Full Stacktrace</summary>

```
[Render thread/INFO] (class_2983): [STDERR]: java.util.concurrent.ExecutionException: net.minecraft.class_148: Getting tooltips
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2092)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.get(AsyncSearchManager.java:114)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.updateSearch(EntryListWidget.java:437)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.lambda$init$6(ScreenOverlayImpl.java:240)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget.onChanged(TextFieldWidget.java:173)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget.addText(TextFieldWidget.java:167)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.basewidgets.TextFieldWidget.method_25400(TextFieldWidget.java:366)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.gui.widget.search.OverlaySearchField.method_25400(OverlaySearchField.java:292)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25400(ScreenOverlayImpl.java:651)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$19(RoughlyEnoughItemsCoreClient.java:331)
[Render thread/INFO] (class_2983): [STDERR]: 	at dev.architectury.impl.fabric.ScreenInputDelegate$DelegateScreen.method_25400(ScreenInputDelegate.java:49)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_309.method_1458(class_309.java:448)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:490)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_309.method_1457(class_309.java:448)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_309.method_22677(class_309.java:463)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:101)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_309.method_22675(class_309.java:463)
[Render thread/INFO] (class_2983): [STDERR]: 	at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
[Render thread/INFO] (class_2983): [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[Render thread/INFO] (class_2983): [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[Render thread/INFO] (class_2983): [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:165)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_1041.method_15998(class_1041.java:310)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1137)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:728)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:217)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[Render thread/INFO] (class_2983): [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[Render thread/INFO] (class_2983): [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[Render thread/INFO] (class_2983): [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[Render thread/INFO] (class_2983): [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[Render thread/INFO] (class_2983): [STDERR]: Caused by: net.minecraft.class_148: Getting tooltips
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.util.CrashReportUtils.throwReport(CrashReportUtils.java:67)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:70)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Render thread/INFO] (class_2983): [STDERR]: Caused by: java.lang.IllegalArgumentException: io.github.queerbric.inspecio.tooltip
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.lang.ClassLoader.definePackage(ClassLoader.java:2204)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.definePackage(KnotClassLoader.java:213)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:145)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
[Render thread/INFO] (class_2983): [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_1799.handler$big000$getTooltipData(class_1799.java:3790)
[Render thread/INFO] (class_2983): [STDERR]: 	at net.minecraft.class_1799.method_32347(class_1799.java:108)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:340)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:181)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:81)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186)
[Render thread/INFO] (class_2983): [STDERR]: 	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61)
[Render thread/INFO] (class_2983): [STDERR]: 	... 10 more
```
</details>

This looks like another victim of https://github.com/shedaniel/RoughlyEnoughItems/issues/517, haven't had it happen when async search is turned off.

The relevant part is
> Caused by: java.lang.IllegalArgumentException: io.github.queerbric.inspecio.tooltip
	at java.base/java.lang.ClassLoader.definePackage(ClassLoader.java:2204)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.definePackage(KnotClassLoader.java:213)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:145)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_1799.handler$big000$getTooltipData(class_1799.java:3790)

Looking into this, the javadocs say `ClassLoader.definePackage()` throws an `IllegalArgumentException` if
> package name duplicates an existing package either in this class loader or one of its ancestors

So what happens is probably that `getTooltipData()` is called on multiple threads which loads multiple of Inspecio's `TooltipComponent` classes at the same time, which ultimately makes `ClassLoader.definePackage()` fail because it's already been defined on another thread...?

And now I'm not sure if this is actually an issue with REI or with Fabric Loaders' `KnotClassLoader`, because it is marked as being [parallel capable](https://github.com/FabricMC/fabric-loader/blob/d7a7e9ccfd895263fcc60aad0bc1148392874c06/src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassLoader.java#L222) - does this mean this is actually a Fabric Loader bug?

**Comment by Fourmisain** [comment]
Fixed in https://github.com/FabricMC/fabric-loader/commit/b6d014bc5dff45646ca4dbbedaf28afe542e833f
