### ISSUE TITLE
Crash with Indrev 0.12.0 when searching in REI

### ISSUE THREAD

**Issue by Justsnoopy30** [Queerbric/Inspecio#41]
Reported exception thrown!
net.minecraft.class_148: Getting tooltips
at net.minecraft.class_437.method_25412(class_437.java:495)
at net.minecraft.class_309.method_1457(class_309.java:448)
at net.minecraft.class_309.method_22677(class_309.java:463)
at net.minecraft.class_1255.execute(class_1255.java:101)
at net.minecraft.class_309.method_22675(class_309.java:463)
at org.lwjgl.glfw.GLFWCharModsCallbackI.callback(GLFWCharModsCallbackI.java:39)
at org.lwjgl.system.JNI.invokeV(Native Method)
at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:190)
at net.minecraft.class_310.method_1523(class_310.java:1140)
at net.minecraft.class_310.method_1514(class_310.java:728)
at net.minecraft.client.main.Main.main(Main.java:217)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:65)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.ClassCastException: class me.steven.indrev.gui.tooltip.modular.ModularTooltipData cannot be cast to class io.github.queerbric.inspecio.tooltip.ConvertibleTooltipData (me.steven.indrev.gui.tooltip.modular.ModularTooltipData and io.github.queerbric.inspecio.tooltip.ConvertibleTooltipData are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @5d066c7d)
at net.minecraft.class_1799.handler$cmb000$getTooltipData(io/github/queerbric/inspecio/mixin/ItemStackMixin.java [inspecio.mixins.json]:165)
at net.minecraft.class_1799.method_32347(class_1799.java:108)
at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getTooltip(ItemEntryDefinition.java:340)
at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:183)
at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:81)
at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:217)
at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:202)
at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:186)
at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:61)
at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:49)
at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Justsnoopy30** [comment]
https://github.com/GabrielOlvH/Industrial-Revolution/issues/355
