### ISSUE TITLE
1.18: beacon crashes the game

### ISSUE THREAD

**Issue by MeeniMc** [Queerbric/Inspecio#50]
When hovering a beacon, the following `null` crashes the game.
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10573(String, int)" because "tag" is null
	at io.github.queerbric.inspecio.Inspecio.getRawEffectFromTag(Inspecio.java:196)
	at net.minecraft.class_1747.method_32346(class_1747.java:3563)
	at net.minecraft.class_1799.method_32347(class_1799.java:104)
	at net.minecraft.class_437.method_25409(class_437.java:169)
	at net.minecraft.class_481.method_25409(class_481.java:733)
	at net.minecraft.class_465.method_2380(class_465.java:190)
	at net.minecraft.class_481.method_25394(class_481.java:694)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
```

**Comment by MeeniMc** [comment]
Fixed as of d3d27f3232
