### ISSUE TITLE
Last version for 1.18.2 crashing

### ISSUE THREAD

**Issue by itsMarkiS** [Queerbric/Inspecio#75]
The game does not start when using the last version of the mod for 1.18.2

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @758705fa; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @ebaa6cb, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @758705fa; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.minecraft.class_155.<clinit>(class_155.java:214)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	... 2 more

**Comment by LambdAurora** [comment]
Inspecio 1.3.0 for Minecraft 1.18.2 is no longer supported. Inspecio is now on the Quilt Loader.
