### ISSUE TITLE
Inspecio is breaking the game with a weird crash message lol

### ISSUE THREAD

**Issue by itsMarkiS** [Queerbric/Inspecio#78]
The game keeps crashing and doesnt even starts..... how can i fix it? tried removig a lot of mods but nothing happened, THEN I REMOVED INSPECIO and boom, it worked again...

[main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121 of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @39fcbef6; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.LinkageError: loader constraint violation: when resolving field "BUILT_IN_EXCEPTIONS" of type com.mojang.brigadier.exceptions.BuiltInExceptionProvider, the class loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121 of the current class, net.minecraft.class_155, and the class loader 'app' for the field's defining class, com.mojang.brigadier.exceptions.CommandSyntaxException, have different Class objects for type com.mojang.brigadier.exceptions.BuiltInExceptionProvider (net.minecraft.class_155 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66565121, parent loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader$DynamicURLClassLoader @39fcbef6; com.mojang.brigadier.exceptions.CommandSyntaxException is in unnamed module of loader 'app')
	at net.minecraft.class_155.<clinit>(class_155.java:214) ~[client-intermediary.jar:?]
	at net.minecraft.class_3797.<init>(class_3797.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_3797.<clinit>(class_3797.java:21) ~[client-intermediary.jar:?]
	at fudge.notenoughcrashes.fabric.StacktraceDeobfuscator.<clinit>(StacktraceDeobfuscator.java:29) ~['%20notenoughcrashes-4.1.4+1.18.2-fabric.jar:?]
	at net.minecraft.client.main.Main.handler$bkb000$asSoonAsPossible(Main.java:517) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[fabric-loader-0.13.3-1.18.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more

**Comment by LemmaEOF** [comment]
Didn't you already [file this one](https://github.com/Queerbric/Inspecio/issues/75)?

**Comment by itsMarkiS** [comment]
> Didn't you already [file this one](https://github.com/Queerbric/Inspecio/issues/75)?

welp, its another crash actually xD the old one has been fixed already, but now it stopped working again with a new error message

**Comment by LemmaEOF** [comment]
...Huh. I see the same `"BUILT_IN_EXCEPTIONS"` as in the last one. It might be the same issue hitting another part of code.

**Comment by LambdAurora** [comment]
Inspecio 1.3.0 on Fabric 1.18.2 is no longer supported. Inspecio is now using Quilt Loader.
