### ISSUE TITLE
Server fails when loading this mod on a fabric server

### ISSUE THREAD

**Issue by ChristopherHaws** [Queerbric/Inspecio#80]
I am getting the following error when trying to start my fabric server with this mod installed:

```
[14:42:56] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.5
[14:42:56] [main/WARN]: Mod resolution failed
[14:42:56] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE inspecio 1.3.0+1.18 {depends quilt_tooltip @ [*]}, ROOT_FORCELOAD_SINGLE inspecio 1.3.0+1.18]
[14:42:56] [main/INFO]: Reason: [HARD_DEP inspecio 1.3.0+1.18 {depends quilt_tooltip @ [*]}]
[14:42:56] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, enchdesc, modmenu, fabric-screen-api-v1, fabric-renderer-indigo, accurateblockplacement, tooltipfix, fabric-rendering-v0, autoreconnect, fabric-rendering-v1, fabric-key-binding-api-v1, controlling, spruceui, entityculling, betterthirdperson, fabric-textures-v0, tweakeroo, malilib, advancementinfo, litematica, easiervillagertrading, fabric-blockrenderlayer-v1, lightoverlay, fabric-renderer-registries-v1, minihud, quilt_client_command, fabric-models-v0, no_fog]
[14:42:56] [main/INFO]: Fix: add [add:quilt_tooltip 1 ([(-∞,∞)])], remove [], replace []
[14:42:56] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install quilt_tooltip, any version.
Unmet dependency listing:
	 - Mod 'Inspecio' (inspecio) 1.3.0+1.18 requires any version of quilt_tooltip, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.5.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-server-mc.1.18.2-loader.0.14.5-launcher.0.10.2.jar:0.10.2]

```

**Comment by LemmaEOF** [comment]
Due to technical limitations with Fabric, Inspecio now only works on [Quilt Loader](https://quiltmc.org). Quilt can run just about all Fabric mods, so you can switch to it if you'd like to use Inspecio. Apologies!

**Comment by ChristopherHaws** [comment]
Hmm, I knew that the 1.4.x version was quilt only (havent had a chance to switch my server and client mod pack yet), but the version I am using says it is for fabric. Specifically, this is the version I am using: https://modrinth.com/mod/inspecio/version/1.3.0+1.18

**Comment by LemmaEOF** [comment]
That was because it was made while the Quilt Standard Libraries run on fabric, which they don't any more :< I'm not sure if there's anything that can be done right now

**Comment by ChristopherHaws** [comment]
Ok thanks. I will downgrade to 1 version lower and work on getting my server on quilt. I've been meaning to do this anyways ^_^
