### ISSUE TITLE
Inspecio causing crash when starting a server

### ISSUE THREAD

**Issue by twome** [Queerbric/Inspecio#85]
This was ran with Inspecio v1.3.0 - (the one marked Fabric, not Quilt, on Modrinth) and the latest Fabric server. Also, that same file works perfectly on singleplayer (the latest Fabric client loader) - I copied my whole `mods/` directory verbatim, and I definitely don't have the Quilt standard library or the "quilt_tooltip" module/mod available on SP. Maybe an accidental mixup of the Quilt/Fabric dependencies in the server-only code?

Win 10 x64, 
Java 18.0.1.1

```bash
> java -Xmx2G -jar fabric-server-mc.1.18.2-loader.0.14.6-launcher.0.11.0.jar nogui

Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[02:28:31] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.6
[02:28:31] [ForkJoinPool-1-worker-4/WARN]: Mod cleardespawn uses the version 21w40a-1.1.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '21w40a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[02:28:31] [ForkJoinPool-1-worker-4/WARN]: Mod create uses the version mc1.18.2_v0.4.1+586 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[02:28:31] [ForkJoinPool-1-worker-4/WARN]: Mod registrate-fabric uses the version MC1.18.2-1.0.3 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'MC1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[02:28:31] [ForkJoinPool-1-worker-4/WARN]: Mod strawgolem uses the version 2.0.0a2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0a2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[02:28:31] [ForkJoinPool-1-worker-4/WARN]: Mod theducksmod uses the version fabric-1182-11 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[02:28:31] [ForkJoinPool-1-worker-3/WARN]: The mod "thonkutil-customization-v1" contains invalid entries in its mod json:
- Unsupported root entry "disabled:mixins" at line 11 column 20
[02:28:31] [main/WARN]: Mod resolution failed
[02:28:31] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE inspecio 1.3.0+1.18 {depends quilt_tooltip @ [*]}, ROOT_FORCELOAD_SINGLE inspecio 1.3.0+1.18]
[02:28:31] [main/INFO]: Reason: [HARD_DEP inspecio 1.3.0+1.18 {depends quilt_tooltip @ [*]}]
[02:28:31] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, cleardespawn, fabric-keybindings-v0, stylisheffects, satin, fuelinfo, dcch, pinglist, invmove, tweed4_tailor_screen, clickthrough, fallingleaves, fabric-textures-v0, nmuk, make_bubbles_pop, right-click-clear, cloth-scissors-api-v1, easiervillagertrading, fabric-blockrenderlayer-v1, coat, fabric-renderer-registries-v1, bettertaskbar, skiptransitions, cameraoverhaul, dynamicfps, travelerstitles, sneakycurses, pling, statuseffecttimer, modmenu, bettercontrols, blur, amecsapi, fabric-screen-api-v1, fullscreeno, inventoryhotswap, thonkutil-titlescreen-v1, fabric-renderer-indigo, effective, whats_that_slot, voidfog, charmonium, flywheel, notenoughanimations, fabric-rendering-v0, thonkutil-coords-v1, fabric-key-binding-api-v1, fabric-rendering-v1, betterbiomeblend, disable_custom_worlds_advice, paginatedadvancements, entityculling, betterthirdperson, smokeextender, raised, indium, extrasounds, cull-less-leaves, norecipebook, clear-skies, enhancedblockentities, visuality, tillitbreaks, betterf3, smoothswapping, quilt_client_command, fabric-models-v0, tweed4_tailor_coat, noindium, salutem, presencefootsteps]
[02:28:31] [main/INFO]: Fix: add [add:quilt_tooltip 1 ([(-Ôê×,Ôê×)])], remove [], replace []
[02:28:31] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install quilt_tooltip, any version.
Unmet dependency listing:
         - Mod 'Inspecio' (inspecio) 1.3.0+1.18 requires any version of quilt_tooltip, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.6.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.6-launcher.0.11.0.jar:0.11.0]
```

**Comment by LambdAurora** [comment]
If you open an issue about a crash, please actually include a crash report.

Feel free to reopen once there's a crash report.

**Comment by twome** [comment]
Updated OP

**Comment by LambdAurora** [comment]
Running Inspecio 1.18.2 is not supported on Fabric. Please use [Quilt](https://quiltmc.org) instead, Quilt is able to load Fabric mods.

**Comment by twome** [comment]
Ah okay, thanks, I'm happy to switch to Quilt over Fabric. Would you mind removing this "Fabric" entry for 1.18.2 on Modrinth to save others from confusion?  
![2022-06-05 03_17_33 screenshot](https://user-images.githubusercontent.com/1880526/172022568-56b21a92-2d88-4f79-946f-701dac03a7af.png)
